### ISSUE TITLE
Slapper Rotating 360 - Continuously

### ISSUE THREAD

**Issue by xKurt21** [XenoServers/Smaccer#2]
Hi,

Please do this it would be helpful for other players like me who needs this. It would be helpful when you spawn the entity saying like for eg. Shop, Ranks, Gamemodes, and etc.

Thank you very much!

**Comment by HyperFlareMC** [comment]
I think the thought process behind "Rotating Slappers" was to make it rotate so it's always looking at the player. There might need to be a separate feature for constant 360 rotation, since it's essentially a completely different concept.
